import { CompleteApplication, ApplicationStatus, ApplicationAuditEvent } from "@/types/applications";

export const APPLICATIONS_STORAGE_KEY = "apex_cms_applications_data_v1";

export const INITIAL_COMPLETE_APPLICATIONS: CompleteApplication[] = [
  {
    id: "1",
    applicationNumber: "APP-2026-8801",
    createdAt: "2026-08-01T09:30:00Z",
    updatedAt: "2026-08-04T14:15:00Z",
    status: "submitted",
    academicSession: "Fall 2026",
    admissionCycle: "Undergraduate Regular Admission",
    assignedReviewer: "Kashif Shahzad (Admissions Officer)",
    personal: {
      fullName: "Hamza Ahmed Khan",
      photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80",
      dob: "2005-04-14",
      gender: "Male",
      cnicBForm: "35202-8491023-1",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "B+",
      domicile: "Lahore (Punjab)",
      maritalStatus: "Single",
      fatherName: "Tariq Ahmed Khan",
      motherName: "Farzana Tariq",
    },
    contact: {
      phone: "+92 300 1234567",
      email: "hamza.khan@gmail.com",
      altPhone: "+92 321 4455660",
      currentAddress: "House 42-B, Block G, Gulberg III",
      permanentAddress: "House 42-B, Block G, Gulberg III",
      city: "Lahore",
      district: "Lahore",
      province: "Punjab",
      postalCode: "54660",
    },
    guardian: {
      guardianName: "Tariq Ahmed Khan",
      relationship: "Father",
      guardianCnic: "35202-1122334-1",
      guardianPhone: "+92 300 9876543",
      guardianOccupation: "Civil Engineer (Senior Project Manager)",
      guardianMonthlyIncome: "PKR 350,000",
      guardianAddress: "House 42-B, Block G, Gulberg III, Lahore",
      emergencyContactName: "Farzana Tariq",
      emergencyContactPhone: "+92 321 4455660",
    },
    academicHistory: [
      {
        id: "acad-1",
        level: "Intermediate / A-Levels / HSSC",
        institution: "Punjab College of Science, Lahore",
        qualification: "FSc Pre-Engineering",
        boardOrUniversity: "BISE Lahore",
        rollNumber: "512940",
        passingYear: "2025",
        totalMarks: 1100,
        obtainedMarks: 930,
        percentage: 84.5,
        grade: "A+",
        majorSubjects: ["Mathematics", "Physics", "Chemistry", "English"],
        status: "Completed",
      },
      {
        id: "acad-2",
        level: "Matric / O-Levels / SSC",
        institution: "Divisional Public School (DPS), Model Town, Lahore",
        qualification: "Matriculation (Science)",
        boardOrUniversity: "BISE Lahore",
        rollNumber: "219481",
        passingYear: "2023",
        totalMarks: 1100,
        obtainedMarks: 985,
        percentage: 89.5,
        grade: "A+",
        majorSubjects: ["Biology", "Physics", "Chemistry", "Mathematics"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "BS Computer Science",
      academicLevel: "Undergraduate",
      firstPreference: "BS Computer Science",
      secondPreference: "BS Software Engineering",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
      shiftPreference: "Morning",
    },
    transport: {
      transportRequired: true,
      route: "Route 4 (Gulberg – Model Town – Faisal Town)",
      pickupLocation: "Model Town Link Road Roundabout",
      notes: "Requires morning shift bus service from Stop #6.",
    },
    documents: [
      {
        id: "doc-1",
        type: "Passport Size Photograph",
        title: "Applicant Recent Photo (Blue Background)",
        fileName: "hamza_photo_recent.jpg",
        fileSize: "1.2 MB",
        uploadDate: "2026-08-01",
        fileUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80",
        status: "verified",
      },
      {
        id: "doc-2",
        type: "CNIC / B-Form",
        title: "National Identity Card / Smart Card Copy",
        fileName: "cnic_hamza_front_back.pdf",
        fileSize: "2.4 MB",
        uploadDate: "2026-08-01",
        status: "verified",
      },
      {
        id: "doc-3",
        type: "Intermediate / HSSC Marksheet",
        title: "FSc Pre-Engineering Verified Result Card",
        fileName: "fsc_part2_result_card.pdf",
        fileSize: "3.1 MB",
        uploadDate: "2026-08-01",
        status: "verified",
      },
      {
        id: "doc-4",
        type: "Matriculation Certificate",
        title: "Matric Board Certificate & Marksheet",
        fileName: "matric_certificate_bise_lhr.pdf",
        fileSize: "2.8 MB",
        uploadDate: "2026-08-01",
        status: "verified",
      },
      {
        id: "doc-5",
        type: "Father / Guardian CNIC",
        title: "Father's CNIC Copy",
        fileName: "father_cnic_tariq.pdf",
        fileSize: "1.5 MB",
        uploadDate: "2026-08-01",
        status: "verified",
      },
      {
        id: "doc-6",
        type: "Character Certificate",
        title: "College Character Certificate",
        fileName: "college_character_cert.pdf",
        fileSize: "980 KB",
        uploadDate: "2026-08-02",
        status: "pending",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-01T09:28:45Z",
      specialCircumstances: "None. First choice candidate for Computer Science department.",
      extracurricularActivities: "Inter-School Coding Olympiad 2024 (1st Runner Up), College Basketball Team Captain.",
      notes: "Original marksheets verified against BISE gazette copy.",
      customAnswers: [
        { question: "Why do you want to study BS Computer Science at Apex Institute?", answer: "Apex Institute has world-class lab infrastructure, recognized faculty, and strong industry linkages for software careers." },
        { question: "Do you have any prior programming experience?", answer: "Yes, proficient in Python and basic C++ through self-learning and academic coursework." },
      ],
    },
    history: [
      {
        id: "hist-1",
        action: "Application Submitted",
        timestamp: "2026-08-01T09:30:00Z",
        performedBy: "Hamza Ahmed Khan",
        role: "Applicant",
        newStatus: "submitted",
        note: "Online admission application submitted successfully with 6 documents.",
      },
      {
        id: "hist-2",
        action: "Initial Document Verification Completed",
        timestamp: "2026-08-03T11:20:00Z",
        performedBy: "Nida Yasir",
        role: "Admissions Officer",
        note: "CNIC, FSc Result Card, and Matriculation credentials verified on BISE Lahore portal.",
      },
    ],
  },
  {
    id: "2",
    applicationNumber: "APP-2026-8802",
    createdAt: "2026-08-03T10:15:00Z",
    updatedAt: "2026-08-05T12:00:00Z",
    status: "interview_scheduled",
    academicSession: "Fall 2026",
    admissionCycle: "Undergraduate Regular Admission",
    assignedReviewer: "Prof. Saima Malik (Dean of Management Sciences)",
    personal: {
      fullName: "Zainab Fatima",
      photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      dob: "2006-02-18",
      gender: "Female",
      cnicBForm: "35201-9876543-2",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "O+",
      domicile: "Lahore (Punjab)",
      maritalStatus: "Single",
      fatherName: "Syed Asif Raza",
      motherName: "Shabana Asif",
    },
    contact: {
      phone: "+92 321 9876543",
      email: "zainab.f@gmail.com",
      altPhone: "+92 300 7766554",
      currentAddress: "House 18-C, Phase 5, DHA",
      permanentAddress: "House 18-C, Phase 5, DHA",
      city: "Lahore",
      district: "Lahore",
      province: "Punjab",
      postalCode: "54792",
    },
    guardian: {
      guardianName: "Syed Asif Raza",
      relationship: "Father",
      guardianCnic: "35201-1122334-9",
      guardianPhone: "+92 321 5566778",
      guardianOccupation: "Chartered Accountant / Director Finance",
      guardianMonthlyIncome: "PKR 450,000",
      guardianAddress: "House 18-C, Phase 5, DHA, Lahore",
      emergencyContactName: "Shabana Asif",
      emergencyContactPhone: "+92 300 7766554",
    },
    academicHistory: [
      {
        id: "acad-3",
        level: "Intermediate / A-Levels / HSSC",
        institution: "Beaconhouse College Campus, Gulberg",
        qualification: "Cambridge GCE A-Levels",
        boardOrUniversity: "Cambridge Assessment International Education",
        rollNumber: "PK042-9912",
        passingYear: "2025",
        totalMarks: 300,
        obtainedMarks: 234,
        percentage: 78.0,
        grade: "A, B, B",
        majorSubjects: ["Business Studies", "Economics", "Accounting"],
        status: "Completed",
      },
      {
        id: "acad-4",
        level: "Matric / O-Levels / SSC",
        institution: "Beaconhouse School System",
        qualification: "Cambridge O-Levels (IGCSE)",
        boardOrUniversity: "Cambridge Assessment International Education",
        rollNumber: "PK042-4421",
        passingYear: "2023",
        totalMarks: 800,
        obtainedMarks: 672,
        percentage: 84.0,
        grade: "4 A*s, 3 As",
        majorSubjects: ["Economics", "Accounting", "Mathematics", "English Literature"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "BBA (Bachelor of Business Administration)",
      academicLevel: "Undergraduate",
      firstPreference: "BBA",
      secondPreference: "BS Accounting & Finance",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
      shiftPreference: "Morning",
    },
    transport: {
      transportRequired: false,
      notes: "Own transport (Private car drop-off).",
    },
    documents: [
      {
        id: "doc-201",
        type: "Photograph",
        title: "Recent Photograph",
        fileName: "zainab_profile.jpg",
        fileSize: "1.1 MB",
        uploadDate: "2026-08-03",
        status: "verified",
      },
      {
        id: "doc-202",
        type: "Equivalence Certificate (IBCC)",
        title: "IBCC Equivalence Certificate for A-Levels",
        fileName: "ibcc_equivalence_alevels.pdf",
        fileSize: "2.1 MB",
        uploadDate: "2026-08-03",
        status: "verified",
      },
      {
        id: "doc-203",
        type: "CNIC / Smart Card",
        title: "Applicant Smart Card",
        fileName: "zainab_cnic.pdf",
        fileSize: "1.6 MB",
        uploadDate: "2026-08-03",
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-03T10:14:10Z",
      extracurricularActivities: "President of High School Business Club, MUN Best Delegate Award.",
      customAnswers: [
        { question: "What are your career goals after graduating?", answer: "To work in corporate finance and eventually launch a fintech venture." },
      ],
    },
    history: [
      {
        id: "hist-201",
        action: "Application Submitted",
        timestamp: "2026-08-03T10:15:00Z",
        performedBy: "Zainab Fatima",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-202",
        action: "Under Review by Faculty Committee",
        timestamp: "2026-08-04T15:00:00Z",
        performedBy: "Kashif Shahzad",
        role: "Admissions Officer",
        previousStatus: "submitted",
        newStatus: "under_review",
        note: "IBCC equivalence verified. Forwarded to FMS Dean for interview slot.",
      },
      {
        id: "hist-203",
        action: "Admission Interview Scheduled",
        timestamp: "2026-08-05T12:00:00Z",
        performedBy: "Prof. Saima Malik",
        role: "Dean of Management Sciences",
        previousStatus: "under_review",
        newStatus: "interview_scheduled",
        note: "Interview scheduled for August 25, 2026 at 11:30 AM in Conference Room B.",
      },
    ],
  },
  {
    id: "3",
    applicationNumber: "APP-2026-8803",
    createdAt: "2026-07-28T14:20:00Z",
    updatedAt: "2026-08-02T16:45:00Z",
    status: "accepted",
    academicSession: "Fall 2026",
    admissionCycle: "Intermediate Regular Admissions",
    assignedReviewer: "Engr. Rashid Minhas (Head of Intermediate)",
    personal: {
      fullName: "Muhammad Bilal Raza",
      photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      dob: "2007-09-12",
      gender: "Male",
      cnicBForm: "35202-4567890-3",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "A+",
      domicile: "Rawalpindi (Punjab)",
      maritalStatus: "Single",
      fatherName: "Ghulam Raza",
      motherName: "Sultana Begum",
    },
    contact: {
      phone: "+92 333 4567890",
      email: "bilal.raza@outlook.com",
      currentAddress: "Street 14, Mohallah Satellite Town",
      permanentAddress: "Street 14, Mohallah Satellite Town",
      city: "Rawalpindi",
      district: "Rawalpindi",
      province: "Punjab",
      postalCode: "46000",
    },
    guardian: {
      guardianName: "Ghulam Raza",
      relationship: "Father",
      guardianCnic: "37405-9988112-1",
      guardianPhone: "+92 333 9988771",
      guardianOccupation: "Government Officer (BPS-18, Irrigation Dept)",
      guardianMonthlyIncome: "PKR 220,000",
      guardianAddress: "Satellite Town, Rawalpindi",
      emergencyContactName: "Ghulam Raza",
      emergencyContactPhone: "+92 333 9988771",
    },
    academicHistory: [
      {
        id: "acad-5",
        level: "Matric / O-Levels / SSC",
        institution: "Rawalpindi Public School",
        qualification: "Matriculation (Science)",
        boardOrUniversity: "BISE Rawalpindi",
        rollNumber: "189421",
        passingYear: "2026",
        totalMarks: 1100,
        obtainedMarks: 1003,
        percentage: 91.2,
        grade: "A+",
        majorSubjects: ["Physics", "Chemistry", "Mathematics", "Biology"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "FSc Pre-Engineering",
      academicLevel: "Intermediate",
      firstPreference: "FSc Pre-Engineering",
      secondPreference: "ICS (Computer Science)",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
      shiftPreference: "Morning",
    },
    transport: {
      transportRequired: true,
      route: "Route 1 (Hostel – Main Campus Shuttle)",
      pickupLocation: "Allama Iqbal Boys Hostel Gate",
      notes: "Hostel resident admission approved.",
    },
    documents: [
      {
        id: "doc-301",
        type: "Applicant Photo",
        title: "Passport Photo",
        fileName: "bilal_photo.jpg",
        fileSize: "1.3 MB",
        uploadDate: "2026-07-28",
        status: "verified",
      },
      {
        id: "doc-302",
        type: "Matric Result Card",
        title: "BISE Rawalpindi Matric Result Sheet",
        fileName: "matric_result_1003_marks.pdf",
        fileSize: "2.9 MB",
        uploadDate: "2026-07-28",
        status: "verified",
      },
      {
        id: "doc-303",
        type: "Character Certificate",
        title: "School Character Certificate",
        fileName: "school_char_cert.pdf",
        fileSize: "1.4 MB",
        uploadDate: "2026-07-28",
        status: "verified",
      },
      {
        id: "doc-304",
        type: "Domicile Certificate",
        title: "Punjab Domicile",
        fileName: "punjab_domicile_cert.pdf",
        fileSize: "1.8 MB",
        uploadDate: "2026-07-28",
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-07-28T14:18:00Z",
      notes: "Top merit holder in Pre-Engineering batch.",
    },
    history: [
      {
        id: "hist-301",
        action: "Application Submitted",
        timestamp: "2026-07-28T14:20:00Z",
        performedBy: "Muhammad Bilal Raza",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-302",
        action: "Application Reviewed & Merit Calculated",
        timestamp: "2026-07-30T10:00:00Z",
        performedBy: "Nida Yasir",
        role: "Admissions Officer",
        previousStatus: "submitted",
        newStatus: "under_review",
        note: "Scored 91.2% in Matric Science. High merit ranking.",
      },
      {
        id: "hist-303",
        action: "Admission Accepted",
        timestamp: "2026-08-02T16:45:00Z",
        performedBy: "Engr. Rashid Minhas",
        role: "Head of Intermediate",
        previousStatus: "under_review",
        newStatus: "accepted",
        note: "Official admission offer issued. Fee voucher generated with 25% merit scholarship.",
      },
    ],
  },
  {
    id: "4",
    applicationNumber: "APP-2026-8804",
    createdAt: "2026-08-05T11:00:00Z",
    updatedAt: "2026-08-06T09:30:00Z",
    status: "under_review",
    academicSession: "Fall 2026",
    admissionCycle: "Intermediate Regular Admissions",
    assignedReviewer: "Kashif Shahzad (Admissions Officer)",
    personal: {
      fullName: "Ayesha Siddiqui",
      photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
      dob: "2007-11-20",
      gender: "Female",
      cnicBForm: "35202-5556677-4",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "AB+",
      domicile: "Lahore (Punjab)",
      maritalStatus: "Single",
      fatherName: "Dr. Nadeem Siddiqui",
      motherName: "Sobia Nadeem",
    },
    contact: {
      phone: "+92 311 5556677",
      email: "ayesha.s@hotmail.com",
      currentAddress: "House 120-E, Johar Town",
      permanentAddress: "House 120-E, Johar Town",
      city: "Lahore",
      district: "Lahore",
      province: "Punjab",
      postalCode: "54700",
    },
    guardian: {
      guardianName: "Dr. Nadeem Siddiqui",
      relationship: "Father",
      guardianCnic: "35202-3344556-7",
      guardianPhone: "+92 300 8877665",
      guardianOccupation: "Medical Specialist / Associate Professor",
      guardianMonthlyIncome: "PKR 500,000",
      guardianAddress: "House 120-E, Johar Town, Lahore",
      emergencyContactName: "Dr. Nadeem Siddiqui",
      emergencyContactPhone: "+92 300 8877665",
    },
    academicHistory: [
      {
        id: "acad-6",
        level: "Matric / O-Levels / SSC",
        institution: "Lahore Grammar School (LGS), Johar Town",
        qualification: "Matriculation (Science)",
        boardOrUniversity: "BISE Lahore",
        rollNumber: "319402",
        passingYear: "2026",
        totalMarks: 1100,
        obtainedMarks: 957,
        percentage: 87.0,
        grade: "A+",
        majorSubjects: ["Computer Science", "Physics", "Mathematics", "English"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "ICS (Computer Science)",
      academicLevel: "Intermediate",
      firstPreference: "ICS (Computer Science)",
      secondPreference: "FSc Pre-Engineering",
      campusPreference: "City Campus (Johar Town)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
      shiftPreference: "Morning",
    },
    transport: {
      transportRequired: false,
      notes: "Walkable distance / private transport.",
    },
    documents: [
      {
        id: "doc-401",
        type: "Applicant Photo",
        title: "Recent Photo",
        fileName: "ayesha_pic.png",
        fileSize: "1.5 MB",
        uploadDate: "2026-08-05",
        status: "verified",
      },
      {
        id: "doc-402",
        type: "B-Form Copy",
        title: "NADRA B-Form",
        fileName: "bform_ayesha.pdf",
        fileSize: "2.1 MB",
        uploadDate: "2026-08-05",
        status: "verified",
      },
      {
        id: "doc-403",
        type: "Matric Result Card",
        title: "BISE Lahore Marksheet",
        fileName: "matric_marksheet_957.pdf",
        fileSize: "3.4 MB",
        uploadDate: "2026-08-05",
        status: "pending",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-05T10:58:20Z",
    },
    history: [
      {
        id: "hist-401",
        action: "Application Submitted",
        timestamp: "2026-08-05T11:00:00Z",
        performedBy: "Ayesha Siddiqui",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-402",
        action: "Marked Under Review",
        timestamp: "2026-08-06T09:30:00Z",
        performedBy: "Kashif Shahzad",
        role: "Admissions Officer",
        previousStatus: "submitted",
        newStatus: "under_review",
        note: "Checking subject combinations for Computer Science track.",
      },
    ],
  },
  {
    id: "5",
    applicationNumber: "APP-2026-8805",
    createdAt: "2026-08-08T15:40:00Z",
    updatedAt: "2026-08-10T11:10:00Z",
    status: "rejected",
    academicSession: "Fall 2026",
    admissionCycle: "Intermediate Regular Admissions",
    assignedReviewer: "Engr. Rashid Minhas (Head of Intermediate)",
    personal: {
      fullName: "Ali Hassan",
      photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      dob: "2006-08-10",
      gender: "Male",
      cnicBForm: "35202-3451122-5",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "B-",
      domicile: "Kasur (Punjab)",
      maritalStatus: "Single",
      fatherName: "Hassan Din",
      motherName: "Rasheeda Bibi",
    },
    contact: {
      phone: "+92 345 1122334",
      email: "ali.hassan@gmail.com",
      currentAddress: "Railway Road, Kot Radha Kishan",
      permanentAddress: "Railway Road, Kot Radha Kishan",
      city: "Kasur",
      district: "Kasur",
      province: "Punjab",
      postalCode: "55120",
    },
    guardian: {
      guardianName: "Hassan Din",
      relationship: "Father",
      guardianCnic: "35102-8877112-3",
      guardianPhone: "+92 345 9988112",
      guardianOccupation: "Retail Shopkeeper",
      guardianMonthlyIncome: "PKR 65,000",
      guardianAddress: "Railway Road, Kot Radha Kishan, Kasur",
    },
    academicHistory: [
      {
        id: "acad-7",
        level: "Matric / O-Levels / SSC",
        institution: "Government High School, Kot Radha Kishan",
        qualification: "Matriculation (Science - Private)",
        boardOrUniversity: "BISE Lahore",
        rollNumber: "410294",
        passingYear: "2025",
        totalMarks: 1100,
        obtainedMarks: 534,
        percentage: 48.5,
        grade: "D",
        majorSubjects: ["Biology", "Physics", "Chemistry"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "FSc Pre-Medical",
      academicLevel: "Intermediate",
      firstPreference: "FSc Pre-Medical",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
    },
    transport: {
      transportRequired: true,
      route: "Route 7 (Kasur – Raiwind Express)",
      pickupLocation: "Kot Radha Kishan Railway Stop",
    },
    documents: [
      {
        id: "doc-501",
        type: "Matric Marksheet",
        title: "Matric Result Card",
        fileName: "matric_result_534.pdf",
        fileSize: "1.9 MB",
        uploadDate: "2026-08-08",
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-08T15:35:00Z",
    },
    history: [
      {
        id: "hist-501",
        action: "Application Submitted",
        timestamp: "2026-08-08T15:40:00Z",
        performedBy: "Ali Hassan",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-502",
        action: "Application Rejected",
        timestamp: "2026-08-10T11:10:00Z",
        performedBy: "Engr. Rashid Minhas",
        role: "Head of Intermediate",
        previousStatus: "submitted",
        newStatus: "rejected",
        note: "Eligibility criteria for FSc Pre-Medical is minimum 60% (660 marks). Applicant scored 48.5% (534 marks).",
      },
    ],
  },
  {
    id: "6",
    applicationNumber: "APP-2026-8806",
    createdAt: "2026-08-10T08:45:00Z",
    updatedAt: "2026-08-11T14:20:00Z",
    status: "more_info_required",
    academicSession: "Fall 2026",
    admissionCycle: "Undergraduate Regular Admission",
    assignedReviewer: "Dr. Muhammad Shahbaz (HOD Computer Science)",
    personal: {
      fullName: "Nadia Yasmin",
      photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
      dob: "2005-12-05",
      gender: "Female",
      cnicBForm: "35201-9988776-6",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "A+",
      domicile: "Sahiwal (Punjab)",
      maritalStatus: "Single",
      fatherName: "Yasmin Akhtar Cheema",
      motherName: "Tahira Yasmin",
    },
    contact: {
      phone: "+92 303 9988776",
      email: "nadia.y@gmail.com",
      currentAddress: "Street 9, Tariq Bin Ziyad Colony",
      permanentAddress: "Street 9, Tariq Bin Ziyad Colony, Sahiwal",
      city: "Sahiwal",
      district: "Sahiwal",
      province: "Punjab",
      postalCode: "57000",
    },
    guardian: {
      guardianName: "Yasmin Akhtar Cheema",
      relationship: "Father",
      guardianCnic: "36502-1294812-3",
      guardianPhone: "+92 300 7711223",
      guardianOccupation: "Senior Advocate (High Court)",
      guardianMonthlyIncome: "PKR 300,000",
      guardianAddress: "Tariq Bin Ziyad Colony, Sahiwal",
    },
    academicHistory: [
      {
        id: "acad-8",
        level: "Intermediate / A-Levels / HSSC",
        institution: "Punjab College for Women, Sahiwal",
        qualification: "FSc Pre-Engineering",
        boardOrUniversity: "BISE Sahiwal",
        rollNumber: "618291",
        passingYear: "2025",
        totalMarks: 1100,
        obtainedMarks: 872,
        percentage: 79.3,
        grade: "A",
        majorSubjects: ["Mathematics", "Physics", "Chemistry"],
        status: "Completed",
      },
      {
        id: "acad-9",
        level: "Matric / O-Levels / SSC",
        institution: "Government Girls Higher Secondary School, Sahiwal",
        qualification: "Matriculation (Science)",
        boardOrUniversity: "BISE Sahiwal",
        rollNumber: "119283",
        passingYear: "2023",
        totalMarks: 1100,
        obtainedMarks: 940,
        percentage: 85.5,
        grade: "A+",
        majorSubjects: ["Biology", "Physics", "Chemistry", "Mathematics"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "BS Software Engineering",
      academicLevel: "Undergraduate",
      firstPreference: "BS Software Engineering",
      secondPreference: "BS Computer Science",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
    },
    transport: {
      transportRequired: true,
      route: "Route 2 (Girls Hostel Shuttle)",
      pickupLocation: "Fatima Jinnah Hall",
    },
    documents: [
      {
        id: "doc-601",
        type: "Applicant Photo",
        title: "Photo",
        fileName: "nadia_photo.jpg",
        fileSize: "1.4 MB",
        uploadDate: "2026-08-10",
        status: "verified",
      },
      {
        id: "doc-602",
        type: "FSc Part-2 Result Card",
        title: "BISE Sahiwal FSc Result Card",
        fileName: "fsc_sahiwal_blurry_scan.pdf",
        fileSize: "850 KB",
        uploadDate: "2026-08-10",
        status: "reupload_requested",
        rejectionReason: "Uploaded scan is blurry and the roll number / subject marks are unreadable. Please upload a high-resolution color scan.",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-10T08:40:00Z",
    },
    history: [
      {
        id: "hist-601",
        action: "Application Submitted",
        timestamp: "2026-08-10T08:45:00Z",
        performedBy: "Nadia Yasmin",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-602",
        action: "More Information Requested",
        timestamp: "2026-08-11T14:20:00Z",
        performedBy: "Dr. Muhammad Shahbaz",
        role: "HOD Computer Science",
        previousStatus: "submitted",
        newStatus: "more_info_required",
        note: "Please re-upload a clear scanned copy of your official BISE Sahiwal FSc Part-II result card and your CNIC copy.",
      },
    ],
  },
  {
    id: "7",
    applicationNumber: "APP-2026-8807",
    createdAt: "2026-08-11T16:00:00Z",
    updatedAt: "2026-08-13T10:00:00Z",
    status: "on_hold",
    academicSession: "Fall 2026",
    admissionCycle: "Intermediate Regular Admissions",
    assignedReviewer: "Kashif Shahzad (Admissions Officer)",
    personal: {
      fullName: "Usman Tariq",
      photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
      dob: "2007-03-25",
      gender: "Male",
      cnicBForm: "35201-3344556-7",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "O-",
      domicile: "Gujranwala (Punjab)",
      maritalStatus: "Single",
      fatherName: "Tariq Mehmood",
      motherName: "Nazia Tariq",
    },
    contact: {
      phone: "+92 314 3344556",
      email: "usman.tariq@yahoo.com",
      currentAddress: "Model Town, Gujranwala",
      permanentAddress: "Model Town, Gujranwala",
      city: "Gujranwala",
      district: "Gujranwala",
      province: "Punjab",
      postalCode: "52250",
    },
    guardian: {
      guardianName: "Tariq Mehmood",
      relationship: "Father",
      guardianCnic: "34101-9988441-5",
      guardianPhone: "+92 314 9988112",
      guardianOccupation: "Businessman (Textile Trader)",
      guardianMonthlyIncome: "PKR 180,000",
    },
    academicHistory: [
      {
        id: "acad-10",
        level: "Matric / O-Levels / SSC",
        institution: "Comprehensive High School, Gujranwala",
        qualification: "Matriculation (Arts / General)",
        boardOrUniversity: "BISE Gujranwala",
        rollNumber: "518290",
        passingYear: "2026",
        totalMarks: 1100,
        obtainedMarks: 792,
        percentage: 72.0,
        grade: "B",
        majorSubjects: ["General Science", "General Mathematics", "Civics", "Economics"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "I.Com (Commerce)",
      academicLevel: "Intermediate",
      firstPreference: "I.Com",
      secondPreference: "FA (Arts)",
      campusPreference: "City Campus (Johar Town)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
    },
    transport: {
      transportRequired: false,
    },
    documents: [
      {
        id: "doc-701",
        type: "Matric Marksheet",
        title: "Matric Result Certificate",
        fileName: "matric_result_792.pdf",
        fileSize: "2.1 MB",
        uploadDate: "2026-08-11",
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-11T15:55:00Z",
    },
    history: [
      {
        id: "hist-701",
        action: "Application Submitted",
        timestamp: "2026-08-11T16:00:00Z",
        performedBy: "Usman Tariq",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-702",
        action: "Placed On Hold",
        timestamp: "2026-08-13T10:00:00Z",
        performedBy: "Kashif Shahzad",
        role: "Admissions Officer",
        previousStatus: "submitted",
        newStatus: "on_hold",
        note: "Application placed on hold pending second merit list declaration for I.Com morning quota.",
      },
    ],
  },
  {
    id: "8",
    applicationNumber: "APP-2026-8808",
    createdAt: "2026-08-13T12:30:00Z",
    updatedAt: "2026-08-16T17:00:00Z",
    status: "enrolled",
    academicSession: "Fall 2026",
    admissionCycle: "Undergraduate Regular Admission",
    assignedReviewer: "Prof. Saima Malik (Dean of Management Sciences)",
    personal: {
      fullName: "Sara Nawaz",
      photoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80",
      dob: "2005-06-30",
      gender: "Female",
      cnicBForm: "35201-7788990-2",
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: "B+",
      domicile: "Faisalabad (Punjab)",
      maritalStatus: "Single",
      fatherName: "Muhammad Nawaz Cheema",
      motherName: "Kalsoom Nawaz",
    },
    contact: {
      phone: "+92 322 7788990",
      email: "sara.nawaz@gmail.com",
      currentAddress: "House 54, Susan Road, Madina Town",
      permanentAddress: "House 54, Susan Road, Madina Town, Faisalabad",
      city: "Faisalabad",
      district: "Faisalabad",
      province: "Punjab",
      postalCode: "38000",
    },
    guardian: {
      guardianName: "Muhammad Nawaz Cheema",
      relationship: "Father",
      guardianCnic: "33100-8491029-3",
      guardianPhone: "+92 322 1122334",
      guardianOccupation: "Industrialist / Textile Mill Owner",
      guardianMonthlyIncome: "PKR 750,000",
      guardianAddress: "Susan Road, Faisalabad",
    },
    academicHistory: [
      {
        id: "acad-11",
        level: "Intermediate / A-Levels / HSSC",
        institution: "Punjab College for Women, Faisalabad",
        qualification: "FSc Pre-Engineering",
        boardOrUniversity: "BISE Faisalabad",
        rollNumber: "419204",
        passingYear: "2025",
        totalMarks: 1100,
        obtainedMarks: 974,
        percentage: 88.5,
        grade: "A+",
        majorSubjects: ["Mathematics", "Physics", "Chemistry"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: "BBA (Bachelor of Business Administration)",
      academicLevel: "Undergraduate",
      firstPreference: "BBA",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
    },
    transport: {
      transportRequired: false,
    },
    documents: [
      {
        id: "doc-801",
        type: "Applicant Photo",
        title: "Photo",
        fileName: "sara_photo.jpg",
        fileSize: "1.2 MB",
        uploadDate: "2026-08-13",
        status: "verified",
      },
      {
        id: "doc-802",
        type: "Paid Fee Voucher",
        title: "Admission Fee Paid Challan Copy",
        fileName: "challan_paid_fall2026.pdf",
        fileSize: "2.3 MB",
        uploadDate: "2026-08-16",
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: "2026-08-13T12:28:00Z",
    },
    history: [
      {
        id: "hist-801",
        action: "Application Submitted",
        timestamp: "2026-08-13T12:30:00Z",
        performedBy: "Sara Nawaz",
        role: "Applicant",
        newStatus: "submitted",
      },
      {
        id: "hist-802",
        action: "Admission Accepted",
        timestamp: "2026-08-15T10:00:00Z",
        performedBy: "Prof. Saima Malik",
        role: "Dean of Management Sciences",
        previousStatus: "submitted",
        newStatus: "accepted",
      },
      {
        id: "hist-803",
        action: "Fee Verified & Student Enrolled",
        timestamp: "2026-08-16T17:00:00Z",
        performedBy: "Kashif Shahzad",
        role: "Senior Accounts Officer",
        previousStatus: "accepted",
        newStatus: "enrolled",
        note: "Admission fee paid in full. Roll number BBA-F26-018 assigned.",
      },
    ],
  },
];

// Helper to generate full realistic fallback application if an id isn't explicitly in the INITIAL list
export function createSyntheticApplication(
  id: string,
  appNumber: string,
  name: string,
  phone: string,
  email: string,
  program: string,
  level: "Intermediate" | "Undergraduate",
  date: string,
  status: ApplicationStatus,
  marks: number,
  gender: "Male" | "Female",
  prevQual: string,
  notes?: string
): CompleteApplication {
  const isMale = gender === "Male";
  const firstName = name.split(" ")[0];
  const fatherName = isMale ? `${name.split(" ").slice(-1)[0]} Senior` : `Tariq ${name.split(" ").slice(-1)[0]}`;

  return {
    id,
    applicationNumber: appNumber,
    createdAt: `${date}T10:00:00Z`,
    updatedAt: `${date}T12:30:00Z`,
    status,
    academicSession: "Fall 2026",
    admissionCycle: level === "Undergraduate" ? "Undergraduate Regular Admission" : "Intermediate Regular Admissions",
    assignedReviewer: "Kashif Shahzad (Admissions Officer)",
    personal: {
      fullName: name,
      photoUrl: isMale
        ? `https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80`
        : `https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80`,
      dob: isMale ? "2006-05-15" : "2006-09-22",
      gender,
      cnicBForm: `35202-${Math.floor(1000000 + Math.random() * 9000000)}-${isMale ? 1 : 2}`,
      nationality: "Pakistani",
      religion: "Islam",
      bloodGroup: ["A+", "B+", "O+", "AB+"][Math.floor(Math.random() * 4)],
      domicile: "Lahore (Punjab)",
      maritalStatus: "Single",
      fatherName: `Muhammad ${fatherName}`,
      motherName: `Farida ${fatherName}`,
    },
    contact: {
      phone,
      email,
      altPhone: "+92 300 0000000",
      currentAddress: `House ${Math.floor(Math.random() * 80 + 10)}, Block ${["A", "B", "C", "D", "E"][Math.floor(Math.random() * 5)]}, Model Town`,
      permanentAddress: `House ${Math.floor(Math.random() * 80 + 10)}, Block ${["A", "B", "C", "D", "E"][Math.floor(Math.random() * 5)]}, Model Town`,
      city: "Lahore",
      district: "Lahore",
      province: "Punjab",
      postalCode: "54700",
    },
    guardian: {
      guardianName: `Muhammad ${fatherName}`,
      relationship: "Father",
      guardianCnic: `35202-${Math.floor(1000000 + Math.random() * 9000000)}-1`,
      guardianPhone: phone,
      guardianOccupation: "Senior Business Professional / Engineer",
      guardianMonthlyIncome: "PKR 250,000",
      guardianAddress: "Model Town, Lahore",
      emergencyContactName: `Muhammad ${fatherName}`,
      emergencyContactPhone: phone,
    },
    academicHistory: [
      {
        id: `acad-${id}-1`,
        level: level === "Undergraduate" ? "Intermediate / A-Levels / HSSC" : "Matric / O-Levels / SSC",
        institution: prevQual.split("(")[0]?.trim() || "Superior College",
        qualification: prevQual,
        boardOrUniversity: prevQual.includes("BISE") ? prevQual.match(/\((.*?)\)/)?.[1] || "BISE Lahore" : "BISE Lahore",
        rollNumber: String(400000 + parseInt(id, 10) * 1234),
        passingYear: level === "Undergraduate" ? "2025" : "2026",
        totalMarks: 1100,
        obtainedMarks: Math.round((marks / 100) * 1100),
        percentage: marks,
        grade: marks >= 80 ? "A+" : marks >= 70 ? "A" : marks >= 60 ? "B" : marks >= 50 ? "C" : "D",
        majorSubjects: level === "Undergraduate" ? ["Mathematics", "Physics", "Computer Science"] : ["Science", "Mathematics", "English"],
        status: "Completed",
      },
    ],
    preferences: {
      selectedProgram: program,
      academicLevel: level,
      firstPreference: program,
      secondPreference: level === "Undergraduate" ? "BS Software Engineering" : "ICS (Computer Science)",
      campusPreference: "Main Campus (Gulberg)",
      admissionSession: "Fall 2026",
      admissionCategory: "Open Merit",
      shiftPreference: "Morning",
    },
    transport: {
      transportRequired: parseInt(id, 10) % 2 === 0,
      route: parseInt(id, 10) % 2 === 0 ? "Route 3 (Johar Town – Faisal Town – Main Campus)" : undefined,
      pickupLocation: parseInt(id, 10) % 2 === 0 ? "Allah Hoo Roundabout Stop" : undefined,
    },
    documents: [
      {
        id: `doc-${id}-1`,
        type: "Applicant Photo",
        title: "Recent Passport Size Photograph",
        fileName: `${firstName.toLowerCase()}_photo.jpg`,
        fileSize: "1.1 MB",
        uploadDate: date,
        status: "verified",
      },
      {
        id: `doc-${id}-2`,
        type: "Identity Proof",
        title: "CNIC / Smart B-Form",
        fileName: `cnic_${firstName.toLowerCase()}.pdf`,
        fileSize: "2.3 MB",
        uploadDate: date,
        status: "verified",
      },
      {
        id: `doc-${id}-3`,
        type: "Academic Marksheet",
        title: "Latest Qualification Official Result Card",
        fileName: `result_card_${marks}_pct.pdf`,
        fileSize: "2.7 MB",
        uploadDate: date,
        status: marks >= 50 ? "verified" : "pending",
      },
      {
        id: `doc-${id}-4`,
        type: "Character Certificate",
        title: "Previous College/School Character Certificate",
        fileName: `character_cert.pdf`,
        fileSize: "1.2 MB",
        uploadDate: date,
        status: "verified",
      },
    ],
    declaration: {
      applicantDeclarationAgreed: true,
      declarationDate: `${date}T09:50:00Z`,
      notes: notes || "Standard online submission without special quota request.",
      customAnswers: [
        { question: "Why have you chosen Apex Institute?", answer: "Renowned faculty, modern computer labs, and exceptional graduate placement record." },
      ],
    },
    history: [
      {
        id: `hist-${id}-1`,
        action: "Application Submitted",
        timestamp: `${date}T10:00:00Z`,
        performedBy: name,
        role: "Applicant",
        newStatus: "submitted",
        note: "Submitted online admission form.",
      },
      ...(status !== "submitted"
        ? [
            {
              id: `hist-${id}-2`,
              action: `Status Updated to ${status.replace(/_/g, " ").toUpperCase()}`,
              timestamp: `${date}T12:30:00Z`,
              performedBy: "Kashif Shahzad",
              role: "Admissions Officer",
              previousStatus: "submitted" as ApplicationStatus,
              newStatus: status,
              note: notes || `Application transitioned to ${status}.`,
            },
          ]
        : []),
    ],
  };
}

// 25 Application items matching Admissions table
export const ALL_DEFAULT_APPLICATIONS: CompleteApplication[] = [
  ...INITIAL_COMPLETE_APPLICATIONS,
  createSyntheticApplication("9",  "APP-2026-8809", "Faisal Iqbal",           "+92 300 6677889", "faisal.iqbal@outlook.com",    "BS Computer Science",                "Undergraduate", "2026-08-14", "under_review",        82.0, "Male",   "ICS (BISE Lahore)"),
  createSyntheticApplication("10", "APP-2026-8810", "Maryam Asif",            "+92 333 5544332", "maryam.asif@gmail.com",        "FSc Pre-Medical",                    "Intermediate",  "2026-08-15", "accepted",            93.7, "Female", "Matric Science (BISE Lahore)"),
  createSyntheticApplication("11", "APP-2026-8811", "Danial Shahid",          "+92 312 4455667", "danial.s@gmail.com",           "ICS (Computer Science)",              "Intermediate",  "2026-08-16", "submitted",           76.4, "Male",   "Matric Science (BISE Multan)"),
  createSyntheticApplication("12", "APP-2026-8812", "Rabia Khalid",           "+92 320 3344556", "rabia.k@hotmail.com",          "BBA",                                 "Undergraduate", "2026-08-17", "interview_scheduled", 80.1, "Female", "A-Levels (Beaconhouse)", "Interview: Sep 1"),
  createSyntheticApplication("13", "APP-2026-8813", "Hassan Raza",            "+92 342 6677889", "hassan.raza@gmail.com",        "FSc Pre-Engineering",                "Intermediate",  "2026-08-18", "submitted",           85.9, "Male",   "Matric Science (BISE Bahawalpur)"),
  createSyntheticApplication("14", "APP-2026-8814", "Amna Malik",             "+92 301 8899001", "amna.malik@gmail.com",         "BS Software Engineering",            "Undergraduate", "2026-08-19", "under_review",        77.2, "Female", "FSc Pre-Medical (BISE Lahore)"),
  createSyntheticApplication("15", "APP-2026-8815", "Zubair Ahmed",           "+92 334 0011223", "zubair.a@yahoo.com",           "BS Computer Science",                "Undergraduate", "2026-08-20", "rejected",            44.0, "Male",   "ICS (Private — Repeat)", "Marks below 50% threshold."),
  createSyntheticApplication("16", "APP-2026-8816", "Hira Baig",              "+92 310 2233445", "hira.baig@gmail.com",          "FSc Pre-Medical",                    "Intermediate",  "2026-08-21", "accepted",            89.0, "Female", "Matric Science (BISE DG Khan)"),
  createSyntheticApplication("17", "APP-2026-8817", "Saad Hussain",           "+92 323 4455667", "saad.h@outlook.com",           "I.Com",                               "Intermediate",  "2026-08-22", "enrolled",            81.5, "Male",   "Matric Arts (BISE Sargodha)", "Enrolled — Fall 2026."),
  createSyntheticApplication("18", "APP-2026-8818", "Sana Anjum",             "+92 311 6677889", "sana.anjum@gmail.com",         "BBA",                                 "Undergraduate", "2026-08-23", "submitted",           74.8, "Female", "A-Levels (Army Public School)"),
  createSyntheticApplication("19", "APP-2026-8819", "Imran Butt",             "+92 300 7788990", "imran.butt@gmail.com",         "BS Computer Science",                "Undergraduate", "2026-08-24", "under_review",        83.3, "Male",   "ICS (BISE Lahore)"),
  createSyntheticApplication("20", "APP-2026-8820", "Mehwish Tariq",          "+92 321 0099887", "mehwish.t@hotmail.com",        "FSc Pre-Engineering",                "Intermediate",  "2026-08-25", "submitted",           78.6, "Female", "Matric Science (BISE Lahore)"),
  createSyntheticApplication("21", "APP-2026-8821", "Shahzaib Khan",          "+92 315 1122334", "shahzaib.k@gmail.com",         "ICS (Computer Science)",              "Intermediate",  "2026-08-26", "draft",               68.0, "Male",   "Matric Science (BISE Gujranwala)"),
  createSyntheticApplication("22", "APP-2026-8822", "Faiza Rehman",           "+92 345 3344556", "faiza.rehman@gmail.com",       "BS Software Engineering",            "Undergraduate", "2026-08-27", "accepted",            86.5, "Female", "FSc Pre-Engineering (BISE Faisalabad)"),
  createSyntheticApplication("23", "APP-2026-8823", "Awais Nawaz",            "+92 300 5566778", "awais.nawaz@yahoo.com",        "FSc Pre-Medical",                    "Intermediate",  "2026-08-28", "interview_scheduled", 82.7, "Male",   "Matric Science (BISE Sahiwal)", "Interview: Sep 5"),
  createSyntheticApplication("24", "APP-2026-8824", "Iqra Saleem",            "+92 322 8899001", "iqra.saleem@gmail.com",        "BBA",                                 "Undergraduate", "2026-08-29", "submitted",           75.5, "Female", "I.Com (BISE Lahore)"),
  createSyntheticApplication("25", "APP-2026-8825", "Kamran Ali",             "+92 312 0011223", "kamran.ali@gmail.com",         "BS Computer Science",                "Undergraduate", "2026-08-30", "enrolled",            90.1, "Male",   "ICS (BISE Lahore)", "Enrolled — Fall 2026."),
];

// ─── Status Visual Helpers ───────────────────────────────────────────────────

export interface StatusMeta {
  label: string;
  variant: "default" | "success" | "warning" | "danger" | "info" | "secondary" | "outline";
  badgeClass: string;
  bgLight: string;
  borderLight: string;
  textDark: string;
}

export const APPLICATION_STATUS_CONFIG: Record<ApplicationStatus, StatusMeta> = {
  draft: {
    label: "Draft",
    variant: "outline",
    badgeClass: "bg-slate-100 text-slate-700 border-slate-300",
    bgLight: "bg-slate-50",
    borderLight: "border-slate-200",
    textDark: "text-slate-800",
  },
  submitted: {
    label: "Submitted / Pending",
    variant: "info",
    badgeClass: "bg-sky-50 text-sky-700 border-sky-200",
    bgLight: "bg-sky-50",
    borderLight: "border-sky-200",
    textDark: "text-sky-900",
  },
  under_review: {
    label: "Under Review",
    variant: "warning",
    badgeClass: "bg-amber-50 text-amber-800 border-amber-300",
    bgLight: "bg-amber-50",
    borderLight: "border-amber-200",
    textDark: "text-amber-900",
  },
  more_info_required: {
    label: "More Info Required",
    variant: "warning",
    badgeClass: "bg-purple-50 text-purple-700 border-purple-200",
    bgLight: "bg-purple-50",
    borderLight: "border-purple-200",
    textDark: "text-purple-900",
  },
  on_hold: {
    label: "On Hold",
    variant: "secondary",
    badgeClass: "bg-orange-50 text-orange-700 border-orange-200",
    bgLight: "bg-orange-50",
    borderLight: "border-orange-200",
    textDark: "text-orange-900",
  },
  interview_scheduled: {
    label: "Interview Scheduled",
    variant: "secondary",
    badgeClass: "bg-indigo-50 text-indigo-700 border-indigo-200",
    bgLight: "bg-indigo-50",
    borderLight: "border-indigo-200",
    textDark: "text-indigo-900",
  },
  accepted: {
    label: "Accepted",
    variant: "success",
    badgeClass: "bg-emerald-50 text-emerald-800 border-emerald-300 font-semibold",
    bgLight: "bg-emerald-50",
    borderLight: "border-emerald-200",
    textDark: "text-emerald-950",
  },
  rejected: {
    label: "Rejected",
    variant: "danger",
    badgeClass: "bg-rose-50 text-rose-700 border-rose-200",
    bgLight: "bg-rose-50",
    borderLight: "border-rose-200",
    textDark: "text-rose-900",
  },
  enrolled: {
    label: "Enrolled",
    variant: "success",
    badgeClass: "bg-teal-50 text-teal-800 border-teal-300 font-bold",
    bgLight: "bg-teal-50",
    borderLight: "border-teal-200",
    textDark: "text-teal-950",
  },
};

// ─── Storage Access Methods ──────────────────────────────────────────────────

export function getStoredApplications(): CompleteApplication[] {
  if (typeof window === "undefined") {
    return ALL_DEFAULT_APPLICATIONS;
  }
  try {
    const raw = localStorage.getItem(APPLICATIONS_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(APPLICATIONS_STORAGE_KEY, JSON.stringify(ALL_DEFAULT_APPLICATIONS));
      return ALL_DEFAULT_APPLICATIONS;
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) && parsed.length > 0 ? parsed : ALL_DEFAULT_APPLICATIONS;
  } catch {
    return ALL_DEFAULT_APPLICATIONS;
  }
}

export function saveStoredApplications(apps: CompleteApplication[]) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(APPLICATIONS_STORAGE_KEY, JSON.stringify(apps));
  } catch (err) {
    console.error("Failed to save applications to localStorage:", err);
  }
}

export function findApplicationById(idOrAppNo: string): CompleteApplication | null {
  const all = getStoredApplications();
  const found = all.find(
    (a) => a.id === idOrAppNo || a.applicationNumber.toLowerCase() === idOrAppNo.toLowerCase()
  );
  return found || null;
}

export function updateStoredApplication(
  id: string,
  updater: (prev: CompleteApplication) => CompleteApplication
): CompleteApplication | null {
  const all = getStoredApplications();
  const idx = all.findIndex((a) => a.id === id || a.applicationNumber.toLowerCase() === id.toLowerCase());
  if (idx === -1) return null;

  const updated = updater(all[idx]);
  all[idx] = updated;
  saveStoredApplications(all);
  return updated;
}

export function executeApplicationAction(
  id: string,
  newStatus: ApplicationStatus,
  actionTitle: string,
  note?: string,
  performedBy: string = "Admin / Admissions Officer",
  role: string = "Admissions Staff"
): CompleteApplication | null {
  return updateStoredApplication(id, (prev) => {
    const newAuditEvent: ApplicationAuditEvent = {
      id: `audit-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      action: actionTitle,
      timestamp: new Date().toISOString(),
      performedBy,
      role,
      previousStatus: prev.status,
      newStatus,
      note: note || undefined,
    };

    return {
      ...prev,
      status: newStatus,
      updatedAt: new Date().toISOString(),
      history: [newAuditEvent, ...prev.history],
    };
  });
}
