import { Applicant, Student, Teacher, Staff } from "@/types";

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: "app-2026-001",
    applicationNumber: "APP-2026-8812",
    fullName: "Hamza Ahmed Khan",
    email: "hamza.khan@gmail.com",
    phone: "+92 300 1234567",
    cnicBForm: "35202-1234567-1",
    desiredProgramId: "prog-bs-cs",
    desiredProgramName: "BS Computer Science",
    academicSessionId: "sess-2026-fall",
    previousQualification: "FSc Pre-Engineering (BISE Lahore)",
    previousMarksPercentage: 84.5,
    status: "submitted",
    submissionDate: "2026-08-10",
    applicantNotes: "Submitted metric & intermediate verified marksheets.",
  },
  {
    id: "app-2026-002",
    applicationNumber: "APP-2026-8815",
    fullName: "Zainab Fatima",
    email: "zainab.f@gmail.com",
    phone: "+92 321 9876543",
    cnicBForm: "35201-9876543-2",
    desiredProgramId: "prog-bba",
    desiredProgramName: "Bachelor of Business Administration (BBA)",
    academicSessionId: "sess-2026-fall",
    previousQualification: "A-Levels (Cambridge International)",
    previousMarksPercentage: 78.0,
    status: "interview_scheduled",
    submissionDate: "2026-08-12",
    applicantNotes: "Interview scheduled for Aug 25, 2026 with FMS Dean.",
  },
  {
    id: "app-2026-003",
    applicationNumber: "APP-2026-8820",
    fullName: "Muhammad Bilal Raza",
    email: "bilal.raza@outlook.com",
    phone: "+92 333 4567890",
    cnicBForm: "35202-4567890-3",
    desiredProgramId: "prog-fsc-eng",
    desiredProgramName: "FSc Pre-Engineering",
    academicSessionId: "sess-2025-annual",
    previousQualification: "Matriculation Science (BISE Rawalpindi)",
    previousMarksPercentage: 91.2,
    status: "accepted",
    submissionDate: "2026-08-01",
    applicantNotes: "Fee voucher generated for admission.",
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: "std-2026-001",
    studentIdNumber: "AIST-STD-2024-0101",
    rollNumber: "BCS-F24-014",
    fullName: "Ali Hasan Siddiqui",
    email: "ali.siddiqui@student.apex.edu.pk",
    phone: "+92 301 5551234",
    cnicBForm: "35202-5551234-5",
    programId: "prog-bs-cs",
    programName: "BS Computer Science",
    departmentName: "Department of Computer Science & IT",
    currentSemesterOrYear: 3,
    academicSessionId: "sess-2026-fall",
    status: "active",
    guardianName: "Hasan Raza Siddiqui",
    guardianPhone: "+92 300 5551200",
    admissionDate: "2024-09-01",
    avatarUrl: "/avatars/student1.jpg",
  },
  {
    id: "std-2026-002",
    studentIdNumber: "AIST-STD-2025-0210",
    rollNumber: "BBA-F25-045",
    fullName: "Mahnoor Tariq",
    email: "mahnoor.tariq@student.apex.edu.pk",
    phone: "+92 322 7778899",
    cnicBForm: "35201-7778899-6",
    programId: "prog-bba",
    programName: "Bachelor of Business Administration (BBA)",
    departmentName: "Faculty of Management Sciences",
    currentSemesterOrYear: 2,
    academicSessionId: "sess-2026-fall",
    status: "active",
    guardianName: "Tariq Mahmood Chaudhry",
    guardianPhone: "+92 321 7778800",
    admissionDate: "2025-09-01",
    avatarUrl: "/avatars/student2.jpg",
  },
  {
    id: "std-2026-003",
    studentIdNumber: "AIST-STD-2025-0450",
    rollNumber: "FSC-A25-102",
    fullName: "Usman Ghani",
    email: "usman.ghani@student.apex.edu.pk",
    phone: "+92 345 1122334",
    cnicBForm: "35202-1122334-7",
    programId: "prog-fsc-eng",
    programName: "FSc Pre-Engineering",
    departmentName: "Faculty of Intermediate Sciences",
    currentSemesterOrYear: 2,
    academicSessionId: "sess-2025-annual",
    status: "active",
    guardianName: "Abdul Ghani",
    guardianPhone: "+92 333 1122300",
    admissionDate: "2025-08-15",
  },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "tch-101",
    employeeId: "EMP-TCH-042",
    fullName: "Dr. Muhammad Shahbaz",
    email: "shahbaz@apex.edu.pk",
    phone: "+92 300 4443322",
    departmentId: "dept-cs",
    departmentName: "Department of Computer Science & IT",
    designation: "Associate Professor",
    qualification: "Ph.D. Computer Science (FAST-NUCES)",
    assignedCourseIds: ["crs-cs101", "crs-cs102"],
    joiningDate: "2018-02-15",
  },
  {
    id: "tch-102",
    employeeId: "EMP-TCH-088",
    fullName: "Prof. Saima Malik",
    email: "saima.malik@apex.edu.pk",
    phone: "+92 321 3332211",
    departmentId: "dept-bus",
    departmentName: "Faculty of Management Sciences",
    designation: "Assistant Professor",
    qualification: "MS Management Sciences (LUMS)",
    assignedCourseIds: ["crs-mgt201"],
    joiningDate: "2020-09-01",
  },
  {
    id: "tch-103",
    employeeId: "EMP-TCH-015",
    fullName: "Engr. Rashid Minhas",
    email: "rashid.minhas@apex.edu.pk",
    phone: "+92 334 8887766",
    departmentId: "dept-pre-eng",
    departmentName: "Faculty of Intermediate Sciences",
    designation: "Senior Lecturer",
    qualification: "M.Sc. Applied Physics (UET Lahore)",
    assignedCourseIds: ["crs-phy101"],
    joiningDate: "2016-08-01",
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: "stf-001",
    employeeId: "EMP-ADM-001",
    fullName: "Kashif Shahzad",
    email: "kashif.accounts@apex.edu.pk",
    phone: "+92 300 9988776",
    roleTitle: "Senior Accounts Officer",
    department: "Finance & Accounts",
  },
  {
    id: "stf-002",
    employeeId: "EMP-ADM-005",
    fullName: "Nida Yasir",
    email: "nida.admissions@apex.edu.pk",
    phone: "+92 321 4455667",
    roleTitle: "Admissions Officer",
    department: "Student Affairs & Admissions",
  },
];
